### PR TITLE
Handle data problems

### PR DESCRIPTION
**Pull request by jwestgard**
- update gitignore to ignore alternate log dirs (e.g. logs.local, logs.prod)
- update batch config template to include configurable log location and config
- handle missing metadata elements on issue and page
- handle pages with no files (e.g. pages that were published but not available for digitization)
- omit pages with no files from reel object
- break some long lines

### CODE REVIEW

**Comment by peichman-umd** [comment]
@jwestgard, do you have a sample batch that contains issues with missing images that I can use to test this? If you can put it in the Box folder with the other samples, that would be great.

**Comment by jwestgard** [comment]
@peichman-umd : Yes, I will try to get it done later this pm.

**Comment by jwestgard** [comment]
Test data is in the folder 'test_data' in this directory on Box: https://umd.app.box.com/files/0/f/21078475546/dback_data_problems

This includes one issue with unscanned pages, and one with missing metadata elements.

**Comment by peichman-umd** [comment]
@jwestgard, the call to `item.title` on [line 289 of load.py](https://github.com/jwestgard/newspaper-batchload/blob/d93865ee6ca44698d260845c19a1031365a0fced/load.py#L289) should be wrapped in a `getattr()` call (like `uri` and `creation_timestamp`), since if the item is skipped altogether due to a data read error of the XML file there won't be an issue title to write to the skipfile.

So far, it is still skipping both items in the batch, but I think that may be due to a path issue in my config.

**Comment by peichman-umd** [comment]
It looks like the data read error was because box sync hadn't finished syncing all the files to my workstation. I will give it some time to finish that, then try again.

**Comment by peichman-umd** [comment]
Looks good. We will need to update the pcdm-manifests app to handle pages with missing images, but the loader side is working.

I've created an issue to track the pcdm-manifests work: https://issues.umd.edu/browse/LIBFCREPO-324

**Comment by jwestgard** [comment]
Thanks. To be safe, I'm going to test all the bad data on Dev before doing anything on production.

**Pull request merged**
